# mongod.conf for replica set

# Where to store data
storage:
  dbPath: ./mongodb-data

# Network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1

# Replica set configuration
replication:
  replSetName: rs0

# Logging
systemLog:
  destination: file
  logAppend: true
  path: ./mongodb-data/mongod.log