import React, { useState } from 'react';
import { FileText, Edit, Save, X, Download } from 'lucide-react';
import { Meeting } from '../contexts/MeetingContext';
import { useMeeting } from '../contexts/MeetingContext';

interface MeetingNotesProps {
  meeting: Meeting;
}

export default function MeetingNotes({ meeting }: MeetingNotesProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [notes, setNotes] = useState(meeting.notes || '');
  const { updateMeetingNotes } = useMeeting();

  React.useEffect(() => {
    if (!isEditing && meeting.notes !== notes) {
      setNotes(meeting.notes || '');
    }
  }, [meeting.notes, isEditing]);

  const handleSave = () => {
    updateMeetingNotes(meeting.id, notes);
    setIsEditing(false);
  };

  const handleCancel = () => {
    setNotes(meeting.notes || '');
    setIsEditing(false);
  };

  const exportNotes = () => {
    const content = `Meeting Notes: ${meeting.title}
Date: ${meeting.scheduledTime.toLocaleDateString()}
Platform: ${meeting.platform}

${notes}

---
Generated by MeetBuddyAI`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${meeting.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_notes.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-full flex flex-col p-6">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center space-x-2">
          <FileText className="w-5 h-5 text-indigo-400" />
          <h3 className="font-semibold text-white">Meeting Notes</h3>
        </div>

        <div className="flex space-x-2">
          {meeting.notes && (
            <button
              onClick={exportNotes}
              className="text-slate-400 hover:text-white transition-colors"
              title="Export notes"
            >
              <Download className="w-4 h-4" />
            </button>
          )}

          {!isEditing ? (
            <button
              onClick={() => setIsEditing(true)}
              className="text-slate-400 hover:text-indigo-400 transition-colors"
              title="Edit notes"
            >
              <Edit className="w-4 h-4" />
            </button>
          ) : (
            <div className="flex space-x-1">
              <button
                onClick={handleSave}
                className="text-emerald-400 hover:text-emerald-300 transition-colors"
                title="Save notes"
              >
                <Save className="w-4 h-4" />
              </button>
              <button
                onClick={handleCancel}
                className="text-slate-400 hover:text-rose-400 transition-colors"
                title="Cancel editing"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          )}
        </div>
      </div>

      {isEditing ? (
        <div className="space-y-4 flex-1 flex flex-col">
          <textarea
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            className="flex-1 w-full px-4 py-3 bg-black/20 border border-white/10 rounded-xl text-white placeholder-slate-500 focus:ring-2 focus:ring-indigo-500 focus:border-transparent resize-none transition-all"
            placeholder="Add your meeting notes here...

Key points discussed:
- 
- 

Action items:
- 
- 

Follow-up tasks:
- 
- "
          />
          <div className="flex justify-end space-x-3 mt-4">
            <button
              onClick={handleCancel}
              className="px-4 py-2 bg-white/5 border border-white/10 text-slate-300 rounded-xl hover:bg-white/10 hover:text-white transition-colors text-sm font-medium"
            >
              Cancel
            </button>
            <button
              onClick={handleSave}
              className="px-5 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 text-white rounded-xl hover:from-indigo-400 hover:to-purple-500 transition-all shadow-[0_0_15px_rgba(99,102,241,0.3)] hover:shadow-[0_0_20px_rgba(99,102,241,0.5)] transform hover:-translate-y-0.5 text-sm font-bold"
            >
              Save Notes
            </button>
          </div>
        </div>
      ) : (
        <div className="flex-1 overflow-y-auto custom-scrollbar">
          {meeting.notes ? (
            <div className="prose prose-sm max-w-none">
              <pre className="whitespace-pre-wrap text-slate-300 text-sm leading-relaxed font-sans bg-white/5 p-4 rounded-xl border border-white/5">
                {meeting.notes}
              </pre>
            </div>
          ) : (
            <div className="h-full flex items-center justify-center text-center">
              <div>
                <FileText className="w-12 h-12 text-slate-600 opacity-50 mx-auto mb-3" />
                <p className="text-slate-400 mb-2">No notes added yet</p>
                <button
                  onClick={() => setIsEditing(true)}
                  className="text-indigo-400 hover:text-indigo-300 text-sm font-medium transition-colors"
                >
                  Add meeting notes
                </button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
